# Generated by Django 4.2.7 on 2023-11-04 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='SMTP From Name')),
                ('email', models.EmailField(max_length=100, null=True, verbose_name='SMTP From Email')),
                ('port', models.CharField(max_length=10, null=True, verbose_name='SMTP Port Number')),
                ('host', models.CharField(max_length=50, null=True, verbose_name='SMTP HOST')),
                ('host_user', models.EmailField(max_length=100, null=True, verbose_name='SMTP Host User')),
                ('host_password', models.CharField(max_length=100, null=True, verbose_name='SMTP Host Password')),
                ('use_tls', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=5, null=True, verbose_name='SMTP Use TLS')),
                ('use_ssl', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=5, null=True, verbose_name='SMTP Use SSL')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Under Review', 'Under Review'), ('Draft', 'Draft'), ('Declined', 'Declined')], default='Published', max_length=50, null=True, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name': 'Mail Server',
                'verbose_name_plural': 'Mail Server',
                'db_table': 'settings-mail-server',
            },
        ),
        migrations.CreateModel(
            name='Stripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_key_type', models.CharField(blank=True, choices=[('Live', 'Live'), ('Test', 'Test')], max_length=10, null=True, verbose_name='Stripe Key Type')),
                ('stripe_public_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Public Key')),
                ('stripe_secret_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Secret Key')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Under Review', 'Under Review'), ('Draft', 'Draft'), ('Declined', 'Declined')], default='Published', max_length=50, null=True, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name': 'Stripe Payment Gateway',
                'verbose_name_plural': 'Stripe Payment Gateway',
                'db_table': 'settings-stripe-payment-gateway',
            },
        ),
        migrations.CreateModel(
            name='Twilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountSID', models.CharField(max_length=100, null=True, verbose_name='Account SID')),
                ('authToken', models.CharField(max_length=100, null=True, verbose_name='Auth Token')),
                ('phoneNumber', models.CharField(max_length=20, null=True, verbose_name='Twilio Number')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Under Review', 'Under Review'), ('Draft', 'Draft'), ('Declined', 'Declined')], default='Published', max_length=50, null=True, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name': 'Twilio',
                'verbose_name_plural': 'Twilio',
                'db_table': 'settings-twilio',
            },
        ),
        migrations.CreateModel(
            name='WebSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Brand Name')),
                ('slogan', models.CharField(max_length=255, null=True, verbose_name='Slogan')),
                ('logo_dark', models.ImageField(upload_to='settings/logo/%Y/%m/%d/', verbose_name='Logo Dark')),
                ('logo_light', models.ImageField(upload_to='settings/logo/%Y/%m/%d/', verbose_name='Logo Light')),
                ('favicon', models.FileField(upload_to='settings/favicon/%Y/%m/%d/', verbose_name='Favicon')),
                ('contact_email', models.EmailField(max_length=255, null=True, verbose_name='Contact Email')),
                ('contact_number', models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator('^(\\+?\\d{0,4})?\\s?-?\\s?(\\(?\\d{3}\\)?)\\s?-?\\s?(\\(?\\d{3}\\)?)\\s?-?\\s?(\\(?\\d{4}\\)?)?$', 'The phone number provided is invalid')], verbose_name='Contact Number')),
                ('contact_address', models.CharField(max_length=500, null=True, verbose_name='Contact Address')),
                ('company_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Registered Company Name')),
                ('company_address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Registered Company Address')),
                ('company_gst', models.CharField(blank=True, max_length=50, null=True, verbose_name='Goods and Service Tax')),
                ('default_user', models.ImageField(null=True, upload_to='settings/user/%Y/%m/%d/', verbose_name='Default User Image')),
                ('public_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Google reCaptcha Public Key')),
                ('private_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Google reCaptcha Private Key')),
                ('meta_title', models.CharField(max_length=60, null=True, verbose_name='Meta Title')),
                ('meta_description', models.CharField(max_length=158, null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(max_length=255, null=True, verbose_name='Meta Keywords')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name': 'Web Setting',
                'verbose_name_plural': 'Web Settings',
                'db_table': 'settings-website',
            },
        ),
    ]
