# Generated by Django 4.2.7 on 2023-11-04 06:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Company Name')),
                ('profile', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Company Profile')),
                ('contact', models.CharField(blank=True, max_length=500, null=True, verbose_name='Company Contact')),
                ('website', models.URLField(blank=True, max_length=500, null=True, verbose_name='Company Website')),
                ('address', models.CharField(max_length=500, null=True, verbose_name='Company Address')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m/%d', verbose_name='Company Logo')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Archived', 'Archived')], default='Submitted', max_length=10, null=True, verbose_name='Status')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modifiedDate', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
                'db_table': 'employer-company-list',
            },
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True, verbose_name='Job Title')),
                ('experience', models.CharField(max_length=500, null=True, verbose_name='Experience')),
                ('salary', models.CharField(max_length=500, null=True, verbose_name='Salary')),
                ('location', models.CharField(max_length=500, null=True, verbose_name='Location')),
                ('jd', ckeditor.fields.RichTextField(null=True, verbose_name='Job Description')),
                ('role', models.CharField(max_length=500, null=True, verbose_name='Role')),
                ('industry', models.CharField(max_length=500, null=True, verbose_name='Industry')),
                ('department', models.CharField(max_length=500, null=True, verbose_name='Department')),
                ('roleCategory', models.CharField(max_length=500, null=True, verbose_name='Role Category')),
                ('empType', models.CharField(max_length=500, null=True, verbose_name='Employment Type')),
                ('keySkills', models.CharField(max_length=500, null=True, verbose_name='Key Skills')),
                ('education', models.CharField(max_length=500, null=True, verbose_name='Education')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Archived', 'Archived')], default='Submitted', max_length=10, null=True, verbose_name='Status')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modifiedDate', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employer.company')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'employer-job-list',
            },
        ),
    ]
